### ISSUE TITLE
무가선 전찻길

### ISSUE THREAD

**Issue by Gamunbi** [Gamunbi/Korean-Tram-Set#2]
무가선 트램이나 수소전지 트램 같은, 가공전차선이 필요 없는 전차들만 다닐 수 있는 선로.

~당연히 근현대 구식 전차들은 못 다님.~ 코드 구조상 한계로 불가

**Comment by EightonEight** [comment]
> 무가선 트램은 운행 중간중간 정차시 정거장에 설치된 가공전차선으로 배터리를 충전한다던데, 이건 어떻게 구현할지 고민 필요.

정류장이 있는 타일만 기존 선로로 건설하고, 나머지 구간은 무가선 선로로 건설하면 그래픽만이라도 구현할 수 있을 것 같습니다. (example: #5 )
