### ISSUE TITLE
서울전차 381호 스프라이트 오류

### ISSUE THREAD

**Issue by JukjeonWani** [Gamunbi/Korean-Tram-Set#4]
![화면 캡처 2021-11-26 153338](https://user-images.githubusercontent.com/88026704/143537785-c5d7f147-0312-4bb1-aed7-64cb285bf80f.jpg)
![화면 캡처 2021-11-26 153208](https://user-images.githubusercontent.com/88026704/143537796-eb329c7a-8ca8-4890-b472-06aa872c5c13.jpg)

↓방향 스프라이트에 회사 색상이 적용되지 않습니다

**Comment by Gamunbi** [comment]
0.2.1에서 수정되었습니다.
