### ISSUE TITLE
매립형 전차선로(잔디, 콘크리트)

### ISSUE THREAD

**Issue by EightonEight** [Gamunbi/Korean-Tram-Set#5]
![TRACK_GRASS](https://user-images.githubusercontent.com/77984422/146925550-b00088e3-6d93-499a-b4ec-c33fef6184b4.png)
`TRACK_GRASS`
잔디 마감 선로(무가선)

---

![TRACK_SLAB](https://user-images.githubusercontent.com/77984422/146925557-206e8839-a4e9-4a8c-bc26-37936f8eb916.png)
`TRACK_SLAB`
콘크리트 슬래브 마감 선로

---

도심 구역 내 트램 전용선에 어울리도록 제작하였습니다.

**Example**
![제목 없음](https://user-images.githubusercontent.com/77984422/146926271-73b805ab-50cb-41f1-811c-2f023179a630.png)

**Comment by Gamunbi** [comment]
무가선 선로와 콘크리트 선로 작업해주셔서 감사합니다. 다만 콘크리트 선로도 무가선으로 작업하게 될 듯 싶습니다. 왜냐하면 사실 근대 노면전차들은 모두 케이프 궤간이서 실제로는 현대로템 전차와 근대 전차는 같은 선로에 못 다니기 때문입니다. 

지금 무가선 전차 선로를 작업하게 된다면 아마도 현대 표준궤 전차 전용 선로가 될 것 같습니다.

**Comment by Gamunbi** [comment]
작업해봤는데, 트램선로는 코드 구조상 문제로(디폴트 label인 ELRL을 무조건 덮어씌워야 하는 듯 함), 실제로는 궤간이 다른 근대 전차와 현대로템 전차가 호환되게 할 수밖에 없습니다. 구상했던 몇가지 것들 중 일부는 포기해야 할 듯 싶습니다.

**Comment by Gamunbi** [comment]
![제목 없음](https://user-images.githubusercontent.com/75788864/147274782-3504b51e-774c-403b-aed9-21d77a362c8c.png)
우선 적용해보았습니다.

차량기지 스프라이트는 현재는 디폴트지만 언젠가 수정하겠습니다.

디폴트 선로와 만들어주신 선로가 살짝 색이 다릅니다. 이 부분도 나중에 디폴트 선로의 것으로 수정하겠습니다.

**Comment by EightonEight** [comment]
> 작업해봤는데, 트램선로는 코드 구조상 문제로(디폴트 label인 ELRL을 무조건 덮어씌워야 하는 듯 함), 실제로는 궤간이 다른 근대 전차와 현대로템 전차가 호환되게 할 수밖에 없습니다. 구상했던 몇가지 것들 중 일부는 포기해야 할 듯 싶습니다.

기존 선로를 무조건 덮어씌워야 한다면, 최종 반영 시 사용할 수 있는 전차선로는 무가선 선로만 있는 건지 궁금하네요.

**Comment by Gamunbi** [comment]
가선 선로도 하나 있습니다.

**Comment by Gamunbi** [comment]
완성됨
